name: MLP blob upload

on:
  workflow_dispatch:
  push:
    branches: "main"
    paths: ["templates/mlp/bot.png", "templates/mlp/canvas.png", "templates/mlp/mask.png", "templates/mlp/endu_template.json"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        lfs: true
    
    - name: Copy canvas files
      run: |
          mkdir ./dist
          cp -f ./templates/mlp/bot.png ./templates/mlp/canvas.png ./templates/mlp/mask.png ./templates/mlp/endu_template.json ./dist
    
    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.PONYPLACE_BLOB_CREDS }}
    
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ponyplace --auth-mode login -d '$web' --overwrite true -s ./dist
    
    - name: Azure logout
      run: az logout
      if: always()